version: "3.2"

services:
  api:
    container_name: api
    build: ./api
    environment:
      PG_CONNECTION_STRING: postgres://example:example@climatelocator:5432/climatelocator

    ports:
      - 3000:3000
    volumes:
      - ./api/src:/usr/climatelocator/api/src


  db:
    container_name: climatelocator_api
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: climatelocator
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432